#!/bin/bash

apt update
apt install -y nfs-kernel-server
mkdir /opt/share
chown -R nobody:nogroup /opt/share
echo "/opt/share *(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
systemctl restart nfs-kernel-server
exportfs
